theme: jekyll-theme-cayman
title: Nathaniel Pereyra's Projects
description: This website is where I discuss the various projects that I have worked on as a college student. Due to my University's academic integrity policy, I am unable to share direct code, so I will describe the various projects I have worked on, and the tools that I used
